### ISSUE TITLE
Issues:

### ISSUE THREAD

**Issue by EmmaSweeney** [ACBSmith/george-grey_polynesian-mythology#2]
# General Issues:

- [x] Re-run `se semanticate .` and commit the changes in `appendix-2.xhtml` and `chapter-13.xhtml`.

- [x] `se find-mismatched-dashes .` and `se find-mismatched-diacritics .` have hits. Make sure these are consistent.

- [x] Re-run `se build-images .` and commit the changes.

- [x] The image files should be named `illustration-#.xml` and `illustration-#.svg`. You'll need to rename both the symbols and music files. The links in the LoI will also need readjusting.

# preface-2.xhtml:

- [x] Remove the trailing periods in the table headers.

- [x] In the `<thead>` element, the `<th>` needs to be inside a `<tr>` element.

- [x] In `<b epub:type="z3998:personal-name">The <abbr>Rev.</abbr> <abbr epub:type="z3998:given-name">J. F. H.</abbr> Wholers,</b> ...` move the comma out of the `<b>` element.

- [x] You don't need `z3998:sender` or `se:letter.dateline`. This isn't a letter.

# appendix-1.xhtml:

- [x] For the bridgehead, remove `class="continued"`, since this is only used for a paragraph after a `<blockquote>`. Also, the bridgehead needs the first word to be capitalized and end with a period ([SEMOS 7.2.11.3](https://standardebooks.org/manual/1.8.0/single-page#7.2.11.3)).

- [x] Although the headers `System`, `Intervals`, and `Notation` don't appear in the ToC, they still need to be in `<section>` elements.

- [x] For the music in `<section>` elements, you can move the song headers into the first `<figure>` elements. Then, you can remove those `<section>` elements, since you no longer need them.

- [x] In the song headers, remove the trailing periods.

- [x] The roman numerals need to be capitalized and the trailing periods removed ([SEMOS 8.8.5](https://standardebooks.org/manual/1.8.0/single-page#8.8.5)).

- [x] In `... (<abbr>lib.</abbr> <span epub:type="z3998:roman">v</span>. c. 5) ...`, `c.` needs to be marked as an abbreviation.

- [x] In `... “<i epub:type="se:name.publication.book" xml:lang="fr">Notices et Extraits des <abbr>MSS.</abbr></i>,” t. <span epub:type="z3998:roman">xvi</span>., ...`, `t.` needs to be marked as an abbreviation.

- [x] Remove the quotes around `“<i epub:type="se:name.publication.book" xml:lang="fr">Notices et Extraits des <abbr>MSS.</abbr></i>,”`.

- [x] For the signature, replace `<footer>` with `<div>`. Make sure to target this element in CSS.

- [x] In the signature, replace `<strong>` with `<span epub:type="z3998:signature">`.

- [x] For `<em>“genera of a system,”</em>`, `<em>“diesis”</em>`, and `<em>“saltus”</em>`, you can remove the italics. You don't need both quotes and italics.

- [x] In `... <em>“genus”</em> ...` the double quotes need to be converted to single quotes. You can remove the italics.

# appendix-2.xhtml:

- [x] Since you've got a mixture of prose and verse quotes, place the prose quotes in `<blockquote>`s and format them according to [SEMOS 8.17.3](https://standardebooks.org/manual/1.8.0/single-page#8.17.3). Remove the `<i>` elements in the citations.

# endnotes.xhtml:

- [x] Some of the backlinks are not referencing the correct chapter numbers. Run `se renumber-endnotes -b .` to correct these.

- [x] In note 2, mark `P.` as an abbreviation.

- [x] For `<i epub:type="se:name.publication.book">Idylls of the King</i>`, use `epub:type="se:name.publication.poem` semantics.

- [x] In note 23, remove the period in the `<cite>` element.

- [x] In note 32, mark `tom.` as an abbreviation.

- [x] In notes 32 and 39, `Notices et Extraits des <abbr>MSS.</abbr>` needs italics and book and language semantics.

- [x] In note 35, this is a book title. It needs italics and book and language semantics.

- [x] In note 37, this is a book title. It needs italics and book semantics.

- [x] In note 37 and 44, this is a book title. It needs italics and book semantics. The title should be title cased.

- [x] In note 39, `tom` should be `tom.` and marked as an abbreviation.

- [x] In note 40, this is a book title. It needs italics and book and language semantics.

- [x] In note 45, `English Journal of Education` is a book title and needs italics and book semantics. `Papers on the Rhythm of the Ancient Greek Orators, of the Psalms, Selah, the Evil Eye` and `Papers on Accent and Quantity` are short works and need quotes.

- [x] In notes 46 - 49, mark `Ed.` as an abbreviation.

- [x] The roman numerals need to be capitalized.

# local.css:

- [x] Remove `#000` from all styling. This interferes with screens in dark mode.

- [x] Remove the following CSS. This is only for epigraphs.
```
[epub|type~="z3998:verse"] cite{
	font-style: normal;
	font-variant: small-caps;
	margin-top: 1em;
}
```

- [x] The styling for `#preface-2 table` can be simplified as:
```
#preface-2 table{
	border-collapse: collapse;
	margin: 1em auto;
}
```

**Comment by ACBSmith** [comment]
Some notes:

- Some of the mismatched diacritics are because words with and without macrons are different words. For example, tāranga is a plant, but Taranga is a personal name. There are a few remaining as a result.
- In appendix-1, when you say to move the music's title inside the `<figure>` element, I'm assuming you mean to literally just move the header within the figure, rather than some version of a `<figcaption>`? This does odd things to the spacing of the heading of the fourth piece when you're looking at in on a full width web browser, but it looks good on a narrow display; any suggestions for CSS there?

**Comment by EmmaSweeney** [comment]
It looks like the issue is caused by `max-height: 100vh;` for the `full-page` class. The browser is miscalculating the height, causing overlap. I'll look into it further when I review again.

**Comment by EmmaSweeney** [comment]
# appendix-1.xhtml:

- [x] The images need to be numbered in order of appearance ([SEMOS 2.2.5](https://standardebooks.org/manual/1.8.0/single-page#2.2.5)).

- [x] The image ids need to be identical to the image file names.

# endnotes.xhtml:

- [x] Remove quotes around book titles.

# local.css:

- [x] For `#preface-2 table th` the styling cas be simplified as:
```
#preface-2 table th{
	font-variant: small-caps;
	padding: .5em 1em;
}
```

- I don't think there is any good solution to the full-page images. If you build the epubs, The music looks fine.

# se-lint-ignore.xml:

- [x] You need to ignore lint errors `y-019` for `appendix-1.xhtml` and `t-003` for `chapter-10.xhtml`

**Comment by ACBSmith** [comment]
Addressed!

**Comment by EmmaSweeney** [comment]
Can you address the lint errors before I review again?

**Comment by ACBSmith** [comment]
Done - thanks for pointing those out.

**Comment by EmmaSweeney** [comment]
# appendix-1.xhtml:

- [x] The subsection headers shouldn't appear in the ToC. Revert the `<h3 epub:type="title">` elements to `<header><p>`.

# local.css:

- [x] Delete:
```
[epub|type~="z3998:subchapter"]{
	margin-top: 3em;
}
```
`core.css` applies the right margins.
 
- [x] Delete:
```
figure#illustration-1,
figure#illustration-2,
figure#illustration-3,
figure#illustration-8,
figure#illustration-9,
figure#illustration-10,
figure#illustration-11,
figure#illustration-12,
figure#illustration-13,
figure#illustration-14,
figure#illustration-15-1,
figure#illustration-15-2,
figure#illustration-16,
figure#illustration-17,
figure#illustration-18,
figure#illustration-19{
	max-width: 30em;
}
```
We want max width of images to be 100%.

**Comment by ACBSmith** [comment]
Done, clean, linted.

With the illustration max-width, that was in because I found that without it, the music was unreadable on a large browser window and that the limit wasn't wide enough to interfere with an ereader.
